image: node:14

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/
  # All jobs, by default, can only pull the cache
  policy: pull

stages:
  - install
  - test
  - deploy

install deps:
  stage: install
  script:
    - yarn install
  cache:
    <<: *global_cache
    policy: pull-push

# Lint code with eslint
lint:
  stage: test
  script:
    - yarn lint

build:
  stage: test
  script:
    - yarn build
  cache:
    <<: *global_cache
    policy: pull-push

audit production:
  stage: test
  script:
    - yarn audit
  only:
    - master
    - demo

audit:
  stage: test
  script:
    - yarn audit
  allow_failure: true
  except:
    - master
    - demo

# Run jest tests
test:
  stage: test
  script:
    - yarn test
  coverage: /All\sfiles.*\s+(\d+(?:.\d+)?)/
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

deploy:
  stage: deploy
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish --access public
  only:
    - tags
  except:
    - branches
