image: node:14

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

jest:
  stage: build
  script:
    - yarn install
    - yarn run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

deploy:
  stage: deploy
  script:
    - yarn run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish --access public
  only:
    - tags
